LAYERS = [
    {"name": "0",               "color": 7,   "linetype": "Continuous", "lineweight": -3, "plot": 1},
    {"name": "Defpoints",       "color": 251, "linetype": "Continuous", "lineweight": -3, "plot": 0},
    {"name": "T_clotures",      "color": 7,   "linetype": "Continuous", "lineweight": -3, "plot": 1},
    {"name": "A7-TXT-5",       "color": 143, "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A7-TXT-10",      "color": 153, "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A7-TXT-20",      "color": 163, "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A7-TXT-30",      "color": 173, "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A7-TXT-40",      "color": 183, "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A7-TXT-50",      "color": 193, "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A7-TXT-100",     "color": 203, "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A7-TXT-150",     "color": 213, "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A7-TXT-200",     "color": 223, "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A6-VU 2",        "color": 8,   "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A6-VU",          "color": 5,   "linetype": "Continuous", "lineweight": 5,  "plot": 1},
    {"name": "A2-CHIMASE",     "color": 3,   "linetype": "Continuous", "lineweight": -3, "plot": 1},
    {"name": "A2-CIMAISE H",   "color": -8,  "linetype": "Continuous", "lineweight": 13, "plot": 1},
    {"name": "00-AXE",         "color": 12,  "linetype": "Continuous", "lineweight": -3, "plot": 0},
    {"name": "00- MAD necessaire", "color": 50, "linetype": "Continuous", "lineweight": -3, "plot": 0},
    {"name": "00-cimaise modulables", "color": 7, "linetype": "Continuous", "lineweight": -3, "plot": 1},
    {"name": "A4-SOCLE",       "color": 7,   "linetype": "Continuous", "lineweight": -3, "plot": 1},
    {"name": "A8-ART-cadre",   "color": 8,   "linetype": "Continuous", "lineweight": 9,  "plot": 1},
    {"name": "A8-ART-works photo", "color": 171, "linetype": "Continuous", "lineweight": 5, "plot": 1},
    {"name": "A8-ART-works plan",  "color": 241, "linetype": "Continuous", "lineweight": 5, "plot": 1},
    {"name": "A8-ART-works plan 2", "color": 13, "linetype": "Continuous", "lineweight": 13, "plot": 1},
    {"name": "A8-ART-detail",  "color": 230, "linetype": "Continuous", "lineweight": 9,  "plot": 1},
    {"name": "A8-ART no",      "color": 152, "linetype": "Continuous", "lineweight": 13, "plot": 1},
    {"name": "A8-MULTIMEDIA",  "color": 67,  "linetype": "Continuous", "lineweight": 9,  "plot": 1},
]


TEXT_STYLES = [
    {"name": "Standard", "font": "txt",      "height": 0.0,   "width": 1.0},
    {"name": "AtoY_5",   "font": "arial.ttf", "height": 10.0,  "width": 1.0},
    {"name": "AtoY_10",  "font": "arial.ttf", "height": 20.0,  "width": 1.0},
    {"name": "AtoY_15",  "font": "arial.ttf", "height": 30.0,  "width": 1.0},
    {"name": "AtoY_20",  "font": "arial.ttf", "height": 40.0,  "width": 1.0},
    {"name": "AtoY_30",  "font": "arial.ttf", "height": 60.0,  "width": 1.0},
    {"name": "AtoY_40",  "font": "arial.ttf", "height": 80.0,  "width": 1.0},
    {"name": "AtoY_50",  "font": "arial.ttf", "height": 100.0, "width": 1.0},
    {"name": "AtoY_75",  "font": "arial.ttf", "height": 150.0, "width": 1.0},
    {"name": "AtoY_100", "font": "arial.ttf", "height": 200.0, "width": 1.0},
    {"name": "AtoY_150", "font": "arial.ttf", "height": 300.0, "width": 1.0},
    {"name": "AtoY_200", "font": "arial.ttf", "height": 400.0, "width": 1.0},
    {"name": "JP_50",    "font": "arial.ttf", "height": 90.0,  "width": 1.0},
    {"name": "ARIAL",    "font": "arial.ttf", "height": 0.0,   "width": 1.0},
]
